name: Playground
on:
  workflow_dispatch:
  release:
    types:
      - published
jobs:
  lets-play:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref_name }}
      - name: Set output
        id: set-output
        env:
          VERSION_TAG: ${{ github.event.inputs.versionTag }}
        run: |
          if test -z "$VERSION_TAG"; then
            echo "value=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            echo "value=${VERSION_TAG}" >> $GITHUB_OUTPUT
          fi
          echo $VERSION_TAG
          echo ${{ github.event.inputs.versionTag }}
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
        shell: bash
      - name: Here is the result of set output "${{ steps.set-output.outputs.value }}"
        run: |
          echo Good
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get sha after checkout
        id: get-sha-after-checkout
        run: echo "sha=$(git rev-parse HEAD)" >> $GITHUB_OUTPUT
        shell: bash
      - name: Here is the result of get sha "${{ steps.get-sha-after-checkout.outputs.sha }}"
        run: |
          echo ${{ steps.get-sha-after-checkout.outputs.sha }}
